const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dock', {
  getBudget: () => ipcRenderer.invoke('get-budget'),
  getPaidUsage: () => ipcRenderer.invoke('get-paid-usage'),
  getEnv: () => ipcRenderer.invoke('get-env'),
  checkProviders: () => ipcRenderer.invoke('check-providers'),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  getAutoHide: () => ipcRenderer.invoke('get-auto-hide'),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  setAutoHide: (seconds) => ipcRenderer.invoke('set-auto-hide', seconds),
  setSpeedTier: (tier) => ipcRenderer.invoke('set-speed-tier', tier),
  getSpeedTier: () => ipcRenderer.invoke('get-speed-tier'),
  dockToClaude: () => ipcRenderer.invoke('dock-to-claude'),
  minimizeToBubble: () => ipcRenderer.invoke('minimize-to-bubble'),
  restoreFromBubble: () => ipcRenderer.invoke('restore-from-bubble'),
  hideWindow: () => ipcRenderer.invoke('hide-window'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('toggle-always-on-top'),
  onDockState: (cb) => ipcRenderer.on('dock-state', (_, s) => cb(s)),
  onSetTheme: (cb) => ipcRenderer.on('set-theme', (_, t) => cb(t)),
  onAutoHideChanged: (cb) => ipcRenderer.on('auto-hide-changed', (_, s) => cb(s)),
  moveWindowBy: (dx, dy) => ipcRenderer.invoke('move-window-by', dx, dy),
  sendNotification: (title, body) => ipcRenderer.invoke('send-notification', title, body),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  setIgnoreMouse: (ignore, opts) => ipcRenderer.invoke('set-ignore-mouse', ignore, opts),
  getWindowPos: () => ipcRenderer.invoke('get-window-pos'),
  getPremium: () => ipcRenderer.invoke('get-premium'),
  setOpacity: (val) => ipcRenderer.invoke('set-opacity', val),
  setPremium: (val) => ipcRenderer.invoke('set-premium', val),
  getKeys: () => ipcRenderer.invoke('get-keys'),
  saveKeys: (keys) => ipcRenderer.invoke('save-keys', keys),
  isFirstRun: () => ipcRenderer.invoke('is-first-run'),
  onAutoHideWarning: (cb) => ipcRenderer.on('auto-hide-warning', cb),
  resetAutoHideTimer: () => ipcRenderer.invoke('reset-auto-hide-timer'),
});
